[package]
name = "montecarlo"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.10.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 2
panic = "abort"
#debug = true